# fly.toml app configuration file generated for product-recpients on 2024-09-18T20:45:18+05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'product-recpients'
primary_region = 'sin'

[env]
  NODE_ENV = "production"
  SHOPIFY_API_KEY = "8ca8a34581a6fcfa87cd9467e146c165"
  SHOPIFY_API_SECRET = "8294086081f4996774049f155c49c4b8"
  SHOPIFY_SCOPES = "write_products"
  SHOPIFY_APP_URL = "https://product-recpients.fly.dev"


[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
