# fly.toml app configuration file generated for product-recpients on 2024-09-18T20:45:18+05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'product-recpients'
primary_region = 'sin'

[env]
  NODE_ENV = "production"
  SHOPIFY_API_KEY = "8ca8a34581a6fcfa87cd9467e146c165"
  SHOPIFY_API_SECRET = "8294086081f4996774049f155c49c4b8"
  SHOPIFY_SCOPES = "write_products"
  SHOPIFY_APP_URL = "https://product-recpients.fly.dev"
  FLY_API_TOKEN="FlyV1 fm2_lJPECAAAAAAAB6qXxBDrEhOWE4VfEEvcUnU4rBg5wrVodHRwczovL2FwaS5mbHkuaW8vdjGWAJLOAAyfsh8Lk7lodHRwczovL2FwaS5mbHkuaW8vYWFhL3YxxDw4V9iRwZfM1p6G+nIEB3WStFdkWmoBu+0Bd02EUxBfF49MoYGhM73AzWu9OGAUxPY7thpo5dq8bG7NVKvETuIbpinAxR5t7b+Cs2TBGlnIaO1IkW//KNgE2nl5dR3wW09uEzeqqzSiYjDN3j6xISLnrP+PAE6yWIdPnHQQRhVv2MrhwOOnr7QCvAMT6Q2SlAORgc4ARte6HwWRgqdidWlsZGVyH6J3Zx8BxCDtlvI7+xUFzaL7y+2z6T5TV9jZJ+R8XYXgvibtFtN5aQ==,fm2_lJPETuIbpinAxR5t7b+Cs2TBGlnIaO1IkW//KNgE2nl5dR3wW09uEzeqqzSiYjDN3j6xISLnrP+PAE6yWIdPnHQQRhVv2MrhwOOnr7QCvAMT6cQQeuan7ekAuM5CF3IQk5AT+8O5aHR0cHM6Ly9hcGkuZmx5LmlvL2FhYS92MZgEks5m6/fdzwAAAAEi5BX7F84ADD7JCpHOAAw+yQzEEFSynvmQXAxsCbGJ0wTqZQbEIOPrMyZBd4Q9hDWIJ8mbq2QYYRmXwg6WnYkmCvdNxngs"


[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
