# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8ca8a34581a6fcfa87cd9467e146c165"
name = "receipt-upload"
handle = "receipt-upload"
application_url = "https://basic-immigration-transition-flex.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "custom-form-app.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://basic-immigration-transition-flex.trycloudflare.com/auth/callback",
  "https://basic-immigration-transition-flex.trycloudflare.com/auth/shopify/callback",
  "https://basic-immigration-transition-flex.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
